# Generated by Django 5.2.10 on 2026-01-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistprofile',
            name='availability',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='focus_areas',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='language_proficiencies',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='offers_teletherapy',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='therapist_profiles/'),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='qualifications',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='therapistprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
