# Generated by Django 5.2.10 on 2026-08-13 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_therapistprofile_availability_therapistprofile_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapistprofile',
            name='availability',
        ),
    ]
